[package]
name = "tree-sitter-all-languages"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tree-sitter.workspace = true

tree-sitter-c = "0.21.4"
tree-sitter-cpp = "0.22.3"
tree-sitter-go = "0.21.0"
tree-sitter-java = "0.21.0"
tree-sitter-javascript = "0.21.4"
tree-sitter-scala = "0.22.1"
tree-sitter-python = "0.21.0"
tree-sitter-ruby = "0.21.0"
tree-sitter-rust = "0.21.2"
tree-sitter-typescript = "0.21.2"

# https://github.com/fwcd/tree-sitter-kotlin
tree-sitter-kotlin = "0.3.8"
# https://github.com/DerekStride/tree-sitter-sql
tree-sitter-sequel = "0.3.5"

tree-sitter-c-sharp = { git = "https://github.com/sourcegraph/tree-sitter-c-sharp", rev = "8b2aae93bc4d958171da09a3c4687ac49f92ce4e" }
tree-sitter-dart = { git = "https://github.com/UserNobody14/tree-sitter-dart", rev = "cf72df5d4a623ca705e81bf9e9d264e1fe9d5da0" }
tree-sitter-jsonnet = { git = "https://github.com/kritzcreek/tree-sitter-jsonnet", rev = "bc147652f72a14c9627deae5c9c33a81e452d391" }
tree-sitter-magik = { git = "https://github.com/kritzcreek/tree-sitter-magik", rev = "d7614f9820563598b0e1e009b3e4707f60af405f" }
tree-sitter-matlab = { git = "https://github.com/kritzcreek/tree-sitter-matlab", rev = "762d3ac3daf68cff04c376a42fd793b0f81ab9c1" }
tree-sitter-nickel = { git = "https://github.com/kritzcreek/tree-sitter-nickel", rev = "46a808abaa3d0f460c859af3c3b9467641f13063" }
tree-sitter-perl = { git = "https://github.com/sourcegraph/tree-sitter-perl", rev = "fa0118e558b788c7ebd8646d3d1eea42dcf321ee" }
tree-sitter-pod = { git = "https://github.com/sourcegraph/tree-sitter-pod", rev = "b99354aaa6b11c6d9edda3285567d94ed02c0e34" }

# Not PR-ed, as there is a more comprehensive PR in the upstream repo: https://github.com/apple/tree-sitter-pkl/pull/8
# My personal fork contains the minimal changes to make things build with the latest tree-sitter.
tree-sitter-pkl = { git = "https://github.com/kritzcreek/tree-sitter-pkl", rev = "372ce76dfae3395fcf083df23328c4eb67cc0119" }
tree-sitter-xlsg = { git = "https://github.com/sourcegraph/tree-sitter-xlsg", rev = "deb2a12e617ad5e3720a1464848949cc46b375be" }
tree-sitter-zig = { git = "https://github.com/maxxnino/tree-sitter-zig", rev = "2bac4cc6c697d46a193905fef6d003bfa0bfabfd" }
tree-sitter-hack = { git = "https://github.com/kritzcreek/tree-sitter-hack", rev = "2a1f331c3b43a2262823f788a222e15a264d1062" }
